# -*- mode: ruby -*-
# vi: set ft=ruby :

class Hash
  def slice(*keep_keys)
    h = {}
    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }
    h
  end unless Hash.method_defined?(:slice)
  def except(*less_keys)
    slice(*keys - less_keys)
  end unless Hash.method_defined?(:except)
end

# Vagrant file retrieved from COSC349 lab9 Univeristy of Otago

Vagrant.configure("2") do |config|


  # The AWS provider does not actually need to use a Vagrant box file.
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    

    # The region for Amazon Educate is fixed.
    aws.region = "us-east-1"

    # Force synchronisation of files to the VM's /vagrant directory using rsync
    override.nfs.functional = false
    override.vm.allowed_synced_folder_types = :rsync

    # The keypair_name parameter tells Amazon which public key to use.
    aws.keypair_name = "cosc349-labs-2021"
    # Configure key path on Windows
    override.ssh.private_key_path = "C:\\Users\\tranv\\.ssh\\cosc349-labs-2021.pem"

    # Configure Amazon EC2 instance type (t2.micro is cheap).
    aws.instance_type = "t2.micro"

    # Configure the security groups
    aws.security_groups = ["sg-070fbd48f253a4d9b"]

    # COnfigure the availability zone and corresponding public subnet id
    aws.availability_zone = "us-east-1a"
    aws.subnet_id = "subnet-06292eed6908f0e05"

    # Configure the ami disk (using focal, amd64, hvm:ebs-ssd, hvm, 2021).
    aws.ami = "ami-036490d46656c4818"

    # Use Ubuntu as web username
    override.ssh.username = "ubuntu"
  end

  # Enable provisioning with a shell script.
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2 php libapache2-mod-php php-mysql


     apt-get install mysql-client-core-8.0
      
      # Change VM's webserver's configuration to use shared folder.
      # (Look inside test-website.conf for specifics.)
      cp /vagrant/test-website.conf /etc/apache2/sites-available/

      # install our website configuration and disable the default
      a2ensite test-website
      a2dissite 000-default
      service apache2 reload

     # Initialsise database schema to the rds database
     cat /vagrant/database.sql | mysql -h asgn-db.cujhfzahbjmj.us-east-1.rds.amazonaws.com -P 3306 -u admin -p123456789 sample

   SHELL
end
